global:
  scrape_interval: 5s
  external_labels:
    monitor: 'docker-host-alpha'

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["52.54.154.139:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["52.54.154.139:9100"]

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'loki'
    scrape_interval: 5s
    static_configs:
      - targets: ['loki:3100']
